/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-krakensdr_v2
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_KRAKENSDR_V2_API_H
#define INCLUDED_KRAKENSDR_V2_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_krakensdr_v2_EXPORTS
#define KRAKENSDR_V2_API __GR_ATTR_EXPORT
#else
#define KRAKENSDR_V2_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_KRAKENSDR_V2_API_H */
